site_name: BMS Database
site_url: https://BMS-ZJU.github.io/BMS_Database/
site_description: 基础医学学习网站
repo_name: BMS-ZJU/BMS_Database
repo_url: https://github.com/BMS-ZJU/BMS_Database
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  logo: images/logo_white.png
  favicon: images/ZJUBMS.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit

  custom_dir: overrides

nav:
  - 首页:
    - index.md
  - 紫金港速通:
    - freshman/index.md
    - 选课: freshman/course_selection.md
    - 教材预定: freshman/textbook.md
    - 对外交流: freshman/external_exchange.md
  - 专业必修课程:
    - mandatory/index.md
    - 生物类: 
      - 医学生命基础:
        - 课程主页: mandatory/medical_life_fundamentals/index.md
        - 考试资料:
          - 考试资料总览: mandatory/medical_life_fundamentals/exams/index.md
          - 2024-2025 期末回忆卷: mandatory/medical_life_fundamentals/exams/2024-2025-final-exam-recall.md
          - 2021-2022 期末测试 A/B 卷及参考答案: mandatory/medical_life_fundamentals/exams/2021-2022-final-exams.md
      - 医学科学素养Ⅰ: mandatory/medical_research_literacy_1/index.md
      - 医学科学英语基础: mandatory/essential_english_for_medicial_sciences/index.md
      - 细胞与生物分子Ⅰ:
        - 课程主页: mandatory/molecular_cell_biology_1/index.md
        - 考试资料:
          - 考试资料总览: mandatory/molecular_cell_biology_1/exams/index.md
          - 2024-2025 期末回忆卷: mandatory/molecular_cell_biology_1/exams/2024-2025-final-exam-recall.md
          - 2023-2024 期末回忆卷: mandatory/molecular_cell_biology_1/exams/2023-2024-final-exam-recall.md
          - 2021-2022 期末回忆卷: mandatory/molecular_cell_biology_1/exams/2021-2022-final-exam-recall.md
      - 细胞与生物分子Ⅱ:
        - 课程主页: mandatory/molecular_cell_biology_2/index.md
        - 平时小测:
          - 小测资料总览: mandatory/molecular_cell_biology_2/quizzes/index.md
          - 2025-2026 小测回忆卷: mandatory/molecular_cell_biology_2/quizzes/2025-2026-quizzes.md
          - 2024-2025 小测回忆卷: mandatory/molecular_cell_biology_2/quizzes/2024-2025-quizzes.md
        - 考试资料:
          - 考试资料总览: mandatory/molecular_cell_biology_2/exams/index.md
          - 2024-2025 期末回忆卷: mandatory/molecular_cell_biology_2/exams/2024-2025-final-exam-recall.md
          - 2023-2024 期末回忆卷: mandatory/molecular_cell_biology_2/exams/2023-2024-final-exam-recall.md
      - 遗传与发育Ⅰ:
        - 课程主页: mandatory/genetics_and_developmental_biology_1/index.md
        - 考试资料:
          - 考试资料总览: mandatory/genetics_and_developmental_biology_1/exams/index.md
          - 2024-2025 冬学期期末回忆: mandatory/genetics_and_developmental_biology_1/exams/2024-2025-final-exam-recall.md
          - 2022-2023 冬学期期末回忆: mandatory/genetics_and_developmental_biology_1/exams/2022-2023-final-exam-recall.md
      - 基础医学科学研究技能Ⅰ:
        - 课程主页: mandatory/basic_techniques_in_medical_sciences_1/index.md
        - 考试资料:
          - 考试资料总览: mandatory/basic_techniques_in_medical_sciences_1/exams/index.md
          - 2024-2025 冬学期期末回忆卷: mandatory/basic_techniques_in_medical_sciences_1/exams/2024-2025-winter-final-exam-recall.md
      - 遗传与发育Ⅱ:
        - 课程主页: mandatory/genetics_and_developmental_biology_2/index.md
        - 考试资料:
          - 考试资料总览: mandatory/genetics_and_developmental_biology_2/exams/index.md
          - 2024-2025 夏学期期末回忆卷: mandatory/genetics_and_developmental_biology_2/exams/2024-2025-final-exam-recall.md
          - 2023-2024 夏学期期末回忆卷: mandatory/genetics_and_developmental_biology_2/exams/2023-2024-final-exam-recall.md
    - 基础医学类:
      - 人体结构与功能学:
        - 课程主页: mandatory/structure_and_function_of_the_human_body/index.md
        - 考试资料:
          - 考试资料总览: mandatory/structure_and_function_of_the_human_body/exams/index.md
          - 2024-2025 期末回忆卷: mandatory/structure_and_function_of_the_human_body/exams/2024-2025-final-exam-recall.md
      - 感染与免疫学:
        - 课程主页: mandatory/infectious_diseases_and_immunity/index.md
        - 平时小测:
          - 小测资料总览: mandatory/infectious_diseases_and_immunity/quizzes/index.md
          - 三次小测题目: mandatory/infectious_diseases_and_immunity/quizzes/quizzes.md
        - 期末考试:
          - 考试资料总览: mandatory/infectious_diseases_and_immunity/exams/index.md
          - 2025-2026 期末回忆卷: mandatory/infectious_diseases_and_immunity/exams/2025-2026-final-exam-recall.md
          - 2024-2025 期末回忆卷: mandatory/infectious_diseases_and_immunity/exams/2024-2025-final-exam-recall.md
      - 疾病基础:
        - 课程主页: mandatory/the_basis_for_human_diseases/index.md
        - 平时小测:
          - 小测资料总览: mandatory/the_basis_for_human_diseases/quizzes/index.md
          - 2025-2026 第一次小测: mandatory/the_basis_for_human_diseases/quizzes/2025-2026-quiz-01.md
          - 2025-2026 第二次小测: mandatory/the_basis_for_human_diseases/quizzes/2025-2026-quiz-02.md
          - 2025-2026 第三次小测: mandatory/the_basis_for_human_diseases/quizzes/2025-2026-quiz-03.md
          - 2025-2026 第四次小测: mandatory/the_basis_for_human_diseases/quizzes/2025-2026-quiz-04.md
          - 2025-2026 第五次小测: mandatory/the_basis_for_human_diseases/quizzes/2025-2026-quiz-05.md
        - 考试资料:
          - 考试资料总览: mandatory/the_basis_for_human_diseases/exams/index.md
          - 2025-2026 期末回忆卷: mandatory/the_basis_for_human_diseases/exams/2025-2026-final-exam-recall.md
      - 基础药理学:
        - 课程主页: mandatory/basic_pharmacology/index.md
        - 讨论课:
          - 讨论课总览: mandatory/basic_pharmacology/discussions/index.md
          - 第一次：中枢神经系统药理: mandatory/basic_pharmacology/discussions/01-central-nervous-system.md
          - 第二次：心血管药理: mandatory/basic_pharmacology/discussions/02-cardiovascular.md
          - 第三次：抗感染药物: mandatory/basic_pharmacology/discussions/03-antimicrobial.md
        - 考试资料:
          - 考试资料总览: mandatory/basic_pharmacology/exams/index.md
          - 期末回忆卷: mandatory/basic_pharmacology/exams/2025-2026-final-exam-recall.md
      - 神经科学:
        - 课程主页: mandatory/neuroscience/index.md
        - 平时小测:
          - 小测资料总览: mandatory/neuroscience/quizzes/index.md
          - 线上自测 1+2+3: mandatory/neuroscience/quizzes/quiz-01.md
          - 线上自测 4+5: mandatory/neuroscience/quizzes/quiz-02.md
          - 线上自测 6+7: mandatory/neuroscience/quizzes/quiz-03.md
          - 线上自测 8+9: mandatory/neuroscience/quizzes/quiz-04.md
          - 线上自测 10+11: mandatory/neuroscience/quizzes/quiz-05.md
          - 线上自测 12+13: mandatory/neuroscience/quizzes/quiz-06.md
          - 线上自测 14+15+16: mandatory/neuroscience/quizzes/quiz-07.md
        - 考试资料:
          - 考试资料总览: mandatory/neuroscience/exams/index.md
          - 2025-2026 期末选择题回忆: mandatory/neuroscience/exams/2025-2026-final-exam-recall.md
    - 公共卫生与预防医学类:
      - 实验动物与伦理学:
        - 课程主页: mandatory/experimental_animals_and_ethics/index.md
        - 考试资料:
          - 考试资料总览: mandatory/experimental_animals_and_ethics/exams/index.md
          - 2024-2025 秋学期期末回忆卷: mandatory/experimental_animals_and_ethics/exams/2024-2025-final-exam-recall.md
      - 医学科学素养Ⅱ:
        - 课程主页: mandatory/medical_science_literacy_2/index.md
        - 练习与小测:
          - 资料总览: mandatory/medical_science_literacy_2/quizzes/index.md
          - 练习与课堂示例: mandatory/medical_science_literacy_2/quizzes/practice-and-examples.md
          - 线上小测 1—3: mandatory/medical_science_literacy_2/quizzes/online-quizzes.md
          - 线下小测 4—5: mandatory/medical_science_literacy_2/quizzes/offline-quizzes.md
        - 考试资料:
          - 考试资料总览: mandatory/medical_science_literacy_2/exams/index.md
          - 2025-2026 期末回忆卷: mandatory/medical_science_literacy_2/exams/2025-2026-final-exam-recall.md
      - 临床流行病学与循证医学: mandatory/clinical_epidemiology_and_evidence_based_medicine/index.md
    - 临床医学类:
      - 重要疾病的临床与研究Ⅰ: mandatory/human_diseases_from_clinic_to_research_1/index.md
      - 重要疾病的临床与研究Ⅱ: mandatory/human_diseases_from_clinic_to_research_2/index.md
      - 重要疾病的临床与研究Ⅲ: mandatory/human_diseases_from_clinic_to_research_3/index.md
    - 交叉性课程:
      - 医学生物物理学:
        - 课程主页: mandatory/medical_biophysics/index.md
        - 课程笔记: mandatory/medical_biophysics/notes/index.md
        - 考试资料:
          - 考试资料总览: mandatory/medical_biophysics/exams/index.md
          - 2024-2025 期末回忆卷: mandatory/medical_biophysics/exams/2024-2025-final-exam-recall.md
          - 2023-2024 期末回忆卷: mandatory/medical_biophysics/exams/2023-2024-final-exam-recall.md
          - 2022-2023 期末回忆卷: mandatory/medical_biophysics/exams/2022-2023-final-exam-recall.md
      - 医学大数据与应用:
        - 课程主页: mandatory/medical_big_data_and_application/index.md
        - 考试资料:
          - 考试资料总览: mandatory/medical_big_data_and_application/exams/index.md
          - 2024-2025 期末回忆卷: mandatory/medical_big_data_and_application/exams/2024-2025-final-exam-recall.md
      - 脑与脑机融合:
        - 课程主页: mandatory/brain_and_brain_machine_integrated_systems/index.md
        - 考试资料:
          - 考试资料总览: mandatory/brain_and_brain_machine_integrated_systems/exams/index.md
          - 2024-2025 期末回忆卷: mandatory/brain_and_brain_machine_integrated_systems/exams/2024-2025-final-exam-recall.md
          - 课堂与往年题目示例: mandatory/brain_and_brain_machine_integrated_systems/exams/examples.md
    - 实践教学环节:
      - 基础医学科学研究技能Ⅱ: mandatory/basic_techniques_in_medical_sciences_2/index.md
      - 基础医学科研实践: mandatory/medical_research_practice/index.md
      - 基础医学教育见习:
        - 课程主页: mandatory/educational_probation_of_basis_medicine/index.md
        - 见习任务总览: mandatory/educational_probation_of_basis_medicine/tasks/index.md
        - 说课与试讲: mandatory/educational_probation_of_basis_medicine/assessment/trial-teaching.md
      - 临床实习: mandatory/clinical_practice/index.md

  - 专业选修课程:
    - elective/index.md
    - 感染与免疫学方向:
      - 微生物学与免疫学前沿技术: elective/microbiology_and_immunology_frontier_technologies/index.md
      - 重要传染病的防治基础: elective/important_infectious_disease_prevention_and_treatment_basis/index.md
      - 临床免疫学: elective/clinical_immunology/index.md
    - 分子肿瘤方向:
      - 肿瘤生物学:
        - 课程主页: elective/tumor_biology/index.md
        - 考试资料:
          - 考试资料总览: elective/tumor_biology/exams/index.md
          - 2024-2025 期末回忆卷: elective/tumor_biology/exams/2024-2025-final-exam-recall.md
      - 肿瘤研究策略与应用: elective/tumor_research_strategy_and_application/index.md
      - 临床肿瘤学概论: elective/clinical_oncology_introduction/index.md
    - 专业选修:
      - 演化医学理论及应用: elective/evolutionary_medicine_theory_and_application/index.md
      - 物理化学:
        - 课程主页: elective/physical_chemistry/index.md
        - 考试资料:
          - 考试资料总览: elective/physical_chemistry/exams/index.md
          - 2024-2025 秋冬期中回忆卷: elective/physical_chemistry/exams/2024-2025-midterm-recall.md
      - 科学写作与表达: elective/academic_writing_and_presentation/index.md
      - 概率论与数理统计: elective/probability_and_mathematical_statistic/index.md
      - 医工信交叉前沿进展: elective/advances_at_the_intersection_of_medicine_engineering_and_information_technology/index.md
      - 医学统计学: elective/clinical_medicine_statistics/index.md
      - 法理学: elective/jurisprudence/index.md
      - 组学与精准医学前沿导论: elective/introduction_to_multi_omics_and_precision_medicine/index.md
      - 管理学: elective/fundamentals_of_management/index.md
      - 教育统计学: elective/educational_statistics/index.md
      - 预防医学: elective/preventive_medicine/index.md
      - 医学伦理学与卫生法学: elective/medical_ethics_and_health_law/index.md
      - 卫生学: elective/clinical_hygiene/index.md
      - 卫生事业管理: elective/health_management/index.md
      - 教育心理学: elective/educational_psychology/index.md
      - 法医学: elective/forensic_medicine/index.md
      - 新药研发: elective/new_drug_research_and_development/index.md
      - 全球环境改变与人类健康: elective/global_environmental_changes_and_human_health/index.md
      - 卫生毒理学: elective/health_toxicology/index.md
      - 医学人工智能: elective/artificial_intelligence_in_medicine/index.md
      - 社会医学(乙): elective/social_medicine_b/index.md
      - 环境卫生学: elective/environmental_health_science/index.md
      - 营养与食品卫生学: elective/nutriology_and_food_hygiene/index.md
  - 本科生轮转: 
    - rotation/index.md
  - 政策收集:
    - policy/index.md
  - 资源收集:
    - 错误页面: error.md
  - 飞跃专题:
    - fly/index.md

extra:
  social:
    - icon: material/web-check
      link: https://bms.zju.edu.cn/

copyright: Copyright &copy; 2024-2026 基础医学飞跃手册编委会

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - css/styles.css
  - https://unpkg.com/katex@0/dist/katex.min.css

