> **时间：** 2025.11.6 13:25 - 2025.11.6 17:30  
> **题量：** 2 题 · 100 分

1. A study was conducted to investigate the effect of a new medication on systolic blood pressure. Blood pressure was measured for 8 patients before and after taking the medication:

    | Participant | Pre-Treatment BP <br> (mmHg) | Post-Treatment BP <br> (mmHg) |
    | :---------: | :--------------------------: | :---------------------------: |
    | 1           | 140                          | 150                           |
    | 2           | 150                          | 142                           |
    | 3           | 135                          | 128                           |
    | 4           | 160                          | 180                           |
    | 5           | 145                          | 138                           |
    | 6           | 155                          | 148                           |
    | 7           | 148                          | 170                           |
    | 8           | 142                          | 135                           |

    Please determine if the medication has a significant effect on **changing** blood pressure at alpha = 0.01.


    ---


2. Suppose you want to test whether **smoking status** is associated with **lung diseas**e in a sample of 200 individuals.

    |               | Lung Disease | No Disease | Total |
    | ------------- | :----------: | :--------: | :---: |
    | Smoker        | 65           | 40         | 105   |
    | Non-smoker    | 25           | 75         | 100   |
    | **Total**     | **90**       | **115**    | **205** |

    Please fill the following table with expected frequencies and perform a Chi-square test at alpha = 0.01  
    (<u><b>keep two decimals during your calculation</b></i>).


    |               | Lung Disease | No Disease |
    |---------------|--------------|------------|
    | Smoker        |              |            |
    | Non-smoker    |              |            |
