> **时间：** 2025.11.6 16:20 - 2025.11.6 17:30  
> **题量：** 2 题 · 100 分

1. A researcher wants to test whether **mean systolic blood pressure (SBP)** differs among **three groups** of adults following different diets using one-way ANOVA:

    | **Group**       | **n** | **SBP (mmHg)**          |
    |-----------------| :---: | :---------------------: |
    | A (Low-salt)    | 5     | 118, 122, 119, 121, 120 |
    | B (Regular)     | 5     | 130, 128, 132, 129, 131 |
    | C (High-fat)    | 5     | 135, 138, 134, 136, 137 |

    Please perform the test and draw a conclusion (alpha = 0.05).  
    (<u><b>keep two-decimals during your calculation</b></u>)


    ---

2. Please examine whether **age (x)** is linearly associated with **systolic blood pressure (SBP, y)**.

    | **Patient** | **Age (x, years)** | **SBP (y, mmHg)** |
    | :---------: | :----------------: | :---------------: |
    | 1           | 20                 | 118               |
    | 2           | 25                 | 121               |
    | 3           | 30                 | 127               |
    | 4           | 35                 | 130               |
    | 5           | 40                 | 135               |
    | 6           | 45                 | 142               |

    (1) Please define your model $ y = bx + a $

    (2) Please use F-test to determine if age is significantly associated with SBP (alpha = 0.05).
