> **时间：** 2025.10.30 16:00 - 2025.10.30 17:30  
> **题量：** 2 题 · 100 分

1. A study was conducted to investigate the effect of a new medication on systolic blood pressure. Blood pressure was measured for 8 patients before and after taking the medication:

    | Participant | Pre-Treatment BP <br> (mmHg) | Post-Treatment BP <br> (mmHg) |
    | :---------: | :--------------------------: | :---------------------------: |
    | 1           | 140                          | 130                           |
    | 2           | 150                          | 142                           |
    | 3           | 135                          | 128                           |
    | 4           | 160                          | 152                           |
    | 5           | 145                          | 138                           |
    | 6           | 155                          | 148                           |
    | 7           | 148                          | 142                           |
    | 8           | 142                          | 135                           |

    Please determine if the medication has a significant effect on reducing blood pressure at alpha = 0.05.


    ---

2. Suppose you want to test whether **smoking status** is associated with lung disease in a sample of 200 individuals.

    |                   | Lung Disease | No Disease | Total |
    | ----------------- | :----------: | :--------: | :---: |
    | **Smoker**        | 60           | 40         | 100   |
    | **Non-smoker**    | 30           | 70         | 100   |
    | **Total**         | 90           | 110        | 200   |

    Please fill the following table with expected frequencies and perform a Chi-square test at alpha = 0.05 (<u><b>keep two-decimals during your calculation</b></u>).

    |               | Lung Disease | No Disease |
    |---------------|--------------|------------|
    | Smoker        |              |            |
    | Non-smoker    |              |            |
