---
title: 医学科学素养Ⅱ 练习2 2025-2026学年
---

<center>

<h1 style="color: black">
<b>$2025$ - $2026$ 学年 医学科学素养Ⅱ 练习2</b>
</h1>

<p style="font-size: 13px">
基础医学专业课 线下练习题<br>
2025.10.16, 不计分, 不作考勤
</p>

</center>

---

1. Relationship between SCN levels and self-reported cigarettes smoked per week
    
    | Self-reported cigarettes smoked in past week | Number of students | Percent with SCN ≥ 100 µg/mL |
    |---------------------------------------------|--------------------|-------------------------------|
    | None                                        | 1163               | 3.3                           |
    | 1–4                                         | 70                 | 4.3                           |
    | 5–14                                        | 30                 | 6.7                           |
    | 15–24                                       | 27                 | 29.6                          |
    | 25–44                                       | 19                 | 36.8                          |
    | 45+                                         | 23                 | 65.2                          |
    
    Suppose the self-reports are completely accurate and are representative of the number of eighth-grade students who smoke in the general community. We are considering using an SCN level ≥ 100 µg/mL as a test criterion for identifying cigarette smokers. Regard a student as positive if he or she smokes one or more cigarettes per week.
    
    1) What is the sensitivity of the test for light-smoking students (students who smoke ≤ 14 cigarettes per week)?
    <br><br>
    
    2) What is the specificity of the test?
    <br><br>
    
    ---
    
1. Please calculate the standardized cure rate for hospital A and B.

    | GROUP | Hospital A |             |           | Hospital B |             |           |
    |-------|------------|-------------|-----------|------------|-------------|-----------|
    |       | # of patients | cure | rate | # of patients | cure | rate |
    | 1     | 1000       | 700         | 0.7       | 100        | 90          | 0.9       |
    | 2     | 100        | 20          | 0.2       | 1000       | 400         | 0.4       |
    | sum   | 1100       | 720         | 0.655     | 1100       | 490         | 0.445     |
<br><br>

    ---

3. The probability of men with color blindness in a given population is 0.025. Suppose the ratio of men and women is 8:7. Now select a man randomly, what's the probability that he is color blind?
<br><br>

    ---

4. The death probability of mice injected with a certain drug is 0.45. If 15 mice accepted the injection, what's the probability that at most 12 mice died? (You can use R program)
<br><br>

    ---

5. There are six bacteria in 1 mL water from a pond. What's the probability that we detect 4 bacteria in 1 mL water?
<br><br>

    ---

6. If calls to your cell phone are a Poisson process with a constant rate λ = 2 calls per hour, what's the probability that, if you forget to turn your phone off in a 1.5-hour movie, your phone rings during that time?
<br><br>
